services:
  - type: web
    name: navdrishti-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: SYSTEM_STATUS
        value: PRODUCTION
      - key: CLASSIFICATION
        value: RESTRICTED
